<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>osp</string>
	</array>
	<key>name</key>
	<string>Osprey</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#root</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>char</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>comment</key>
			<string>Character literal</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.osprey</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escape</string>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>comment.block.documentation.excess.osprey</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Documentation line comment</string>
					<key>match</key>
					<string>///.{0,90}(.*)</string>
					<key>name</key>
					<string>comment.block.documentation.osprey</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>/\*\*(?!/)</string>
					<key>comment</key>
					<string>Documentation block comment</string>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.documentation.osprey</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Line comment</string>
					<key>match</key>
					<string>//.*</string>
					<key>name</key>
					<string>comment.line.double-slash.osprey</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>comment</key>
					<string>Delimited comment</string>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.osprey</string>
				</dict>
			</array>
		</dict>
		<key>escape</key>
		<dict>
			<key>comment</key>
			<string>Escape sequence</string>
			<key>match</key>
			<string>\\(?&gt;["'\\0abnrt_-]|u\h{4}|U\h{8})</string>
			<key>name</key>
			<string>constant.character.escape.osprey</string>
		</dict>
		<key>identifier</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>Type name (probably, anyway; if you follow good style!)</string>
					<key>match</key>
					<string>\\?[\p{Lu}][\p{L}\p{Mn}\p{Mc}\p{Nd}\p{Pc}\p{Cf}_]*</string>
					<key>name</key>
					<string>entity.name.type.osprey</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Identifier (regular or escaped)</string>
					<key>match</key>
					<string>\\?[\p{L}_][\p{L}\p{Mn}\p{Mc}\p{Nd}\p{Pc}\p{Cf}_]*</string>
					<key>name</key>
					<string>variable.other.osprey</string>
				</dict>
			</array>
		</dict>
		<key>keyword</key>
		<dict>
			<key>comment</key>
			<string>All kinds of keywords</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>Control flow keywords</string>
					<key>match</key>
					<string>(?&gt;break|catch|do|else|finally|for|if|next|return|throw|try|while|with|yield)\b</string>
					<key>name</key>
					<string>keyword.control.osprey</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Keyword operators</string>
					<key>match</key>
					<string>(?&gt;and|in|is|not|or|refeq|ref|typeof|xor)\b</string>
					<key>name</key>
					<string>keyword.operator.osprey</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Keyword constants</string>
					<key>match</key>
					<string>(?&gt;false|null|true)\b</string>
					<key>name</key>
					<string>constant.language.osprey</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Language variables - this and base</string>
					<key>match</key>
					<string>(?&gt;base|this)\b</string>
					<key>name</key>
					<string>variable.language.osprey</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Storage types</string>
					<key>match</key>
					<string>(?&gt;const|function|var)\b</string>
					<key>name</key>
					<string>storage.type.osprey</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Extension keywords</string>
					<key>match</key>
					<string>__(?&gt;extern|get_argc|init_type|named_const|primitive)\b</string>
					<key>name</key>
					<string>keyword.extension.osprey</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Other keywords</string>
					<key>match</key>
					<string>(?&gt;abstract|class|enum|get|global|inheritable|iter|namespace|new|operator|overridable|override|private|protected|public|set|static|to|use|where)\b</string>
					<key>name</key>
					<string>keyword.other.osprey</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Reserved keywords</string>
					<key>match</key>
					<string>async\b</string>
					<key>name</key>
					<string>invalid.illegal.keyword.osprey</string>
				</dict>
			</array>
		</dict>
		<key>number</key>
		<dict>
			<key>comment</key>
			<string>All kinds of numeric literals</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>Hexadecimal literals</string>
					<key>match</key>
					<string>0[xX]\h+(?:_\h+)*[uU]?</string>
					<key>name</key>
					<string>constant.numeric.osprey</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Decimal literals, both integral and real</string>
					<key>match</key>
					<string>[0-9]+(?:_[0-9]+)*(?:\.[0-9]+(?:[eE][+-]?[0-9]+)?|[kKgGmMtT]?[uU]?)?</string>
					<key>name</key>
					<string>constant.numeric.osprey</string>
				</dict>
			</array>
		</dict>
		<key>punctuation</key>
		<dict>
			<key>comment</key>
			<string>Assorted punctuation</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>@</string>
					<key>name</key>
					<string>keyword.operator.at.osprey</string>
				</dict>
				<dict>
					<key>match</key>
					<string>~|[+|/%&amp;^#$!=]=?|-[&gt;=]?|\*\*?=?|&lt;=&gt;|&gt;&gt;?=?|&lt;&lt;?=?|::=?|\?[?!]</string>
					<key>name</key>
					<string>keyword.operator.osprey</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\(|\)</string>
					<key>name</key>
					<string>meta.brace.round.osprey</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\[|\]</string>
					<key>name</key>
					<string>meta.brace.square.osprey</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\{|\}</string>
					<key>name</key>
					<string>meta.brace.curly.osprey</string>
				</dict>
			</array>
		</dict>
		<key>root</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#char</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#identifier</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#punctuation</string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>[rR]"</string>
					<key>comment</key>
					<string>Verbatim string literal</string>
					<key>end</key>
					<string>"(?!")</string>
					<key>name</key>
					<string>string.quoted.triple.osprey</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>""</string>
							<key>name</key>
							<string>constant.character.escape.osprey</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>comment</key>
					<string>Regular string literal</string>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string.quoted.double.osprey</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.osprey</string>
	<key>uuid</key>
	<string>c883a4ba-1189-4a40-9f0d-bf2511dfb188</string>
</dict>
</plist>
